name: brand
favicon: null
layout_spectrum: 1
typography_spectrum: 0.46928
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#dd4b39'
    - '#3ead5c'
    - '#612699'
    - '#010101'
  brandStrength: 0.1225284228567034
  lightness: 0.75
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
